CREATE TABLE IF NOT EXISTS orders (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_number VARCHAR(100) NOT NULL UNIQUE,
  user_id INT UNSIGNED NULL,
  training_id INT UNSIGNED NOT NULL,
  customer_name VARCHAR(255) NULL,
  customer_email VARCHAR(255) NULL,
  customer_phone VARCHAR(100) NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
  status ENUM('pending','processing','completed','failed','canceled','refunded') NOT NULL DEFAULT 'pending',
  payment_provider VARCHAR(100) NOT NULL DEFAULT 'local_bank',
  bank_order_id VARCHAR(255) NULL,
  bank_order_password VARCHAR(255) NULL,
  bank_hpp_url TEXT NULL,
  bank_status VARCHAR(100) NULL,
  hpp_redirect_url TEXT NULL,
  raw_create_order_response LONGTEXT NULL,
  raw_get_order_response LONGTEXT NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY orders_training_id_index (training_id),
  KEY orders_status_index (status),
  KEY orders_created_at_index (created_at),
  CONSTRAINT orders_training_id_foreign FOREIGN KEY (training_id) REFERENCES trainings(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id INT UNSIGNED NOT NULL,
  payment_provider VARCHAR(100) NOT NULL DEFAULT 'local_bank',
  provider_payment_id VARCHAR(255) NULL,
  provider_transaction_id VARCHAR(255) NULL,
  approval_code VARCHAR(255) NULL,
  amount DECIMAL(10,2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'EUR',
  status ENUM('pending','processing','completed','failed','canceled','refunded') NOT NULL DEFAULT 'pending',
  bank_status VARCHAR(100) NULL,
  paid_at DATETIME NULL,
  canceled_at DATETIME NULL,
  failed_at DATETIME NULL,
  refunded_at DATETIME NULL,
  raw_response LONGTEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY payments_order_id_index (order_id),
  KEY payments_status_index (status),
  CONSTRAINT payments_order_id_foreign FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_logs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id INT UNSIGNED NULL,
  payment_id INT UNSIGNED NULL,
  action VARCHAR(100) NOT NULL,
  status_before VARCHAR(50) NULL,
  status_after VARCHAR(50) NULL,
  request_payload LONGTEXT NULL,
  response_payload LONGTEXT NULL,
  http_status_code INT NULL,
  error_message TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY payment_logs_order_id_index (order_id),
  KEY payment_logs_payment_id_index (payment_id),
  KEY payment_logs_created_at_index (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
